version: "3.9"
services:
  api:
    image: eclipse-temurin:17-jre
    command: ["java", "-jar", "/app/app.jar"]
    volumes:
      - ./app.jar:/app/app.jar
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
