spring:
  application:
    name: backend-api
  config.import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3306/piesdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:/db/migration
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    com.pies: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
  file:
    name: /dev/stdout

security:
  disable: false

server:
  forward-headers-strategy: native