name: Backend Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build JAR
        working-directory: backend
        run: mvn package -DskipTests

      - name: List built JARs (debug)
        working-directory: backend/target
        run: ls -lh

      - name: Rename and move jar to deploy dir
        run: |
          mv backend/target/*.jar backend/app.jar

      - name: List deploy files (debug)
        run: |
          ls -lh backend/app.jar || echo "No app.jar"
          ls -lh backend/docker-compose.yml || echo "No docker-compose.yml"
          ls -lh backend/docker-compose.override.deploy.yml || echo "No override.deploy.yml"
          ls -lh backend/Dockerfile || echo "No Dockerfile"

      - name: Copy deploy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_KEY }}
          port: ${{ secrets.GCP_PORT }}
          source: "backend/app.jar,backend/docker-compose.yml,backend/docker-compose.override.deploy.yml,backend/Dockerfile"
          target: ~/app

      - name: SSH and restart API container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_KEY }}
          port: ${{ secrets.GCP_PORT }}
          script: |
            cd ~/app/backend
<<<<<<< HEAD
            docker compose -f docker-compose.yml -f docker-compose.override.deploy.yml up -d --force-recreate api
=======
            docker compose -f docker-compose.yml -f docker-compose.override.deploy.yml up -d --force-recreate api
>>>>>>> 285a31550f28f3f273afb4c2b6b07e6013893aa6
